name: Build, Publish & Deploy (ECS)

on:
  push:
    branches:
      - main
      - ci
      - staging
      - "*" # feature branches
  workflow_dispatch:
    inputs:
      alb_dns:
        description: "Optional ALB DNS for smoke test (e.g., listservice-ci-alb-xxxx.eu-central-1.elb.amazonaws.com)"
        required: false
      skip_wait:
        description: "Skip waiting for service to stabilize"
        required: false
        default: "false"
      push_latest:
        description: "Also push :latest (for manual runs)"
        required: false
        default: "false"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 920120424372
  ECR_REPO: listservice-global
  IMAGE_CONTEXT: ./listservice-backend
  DOCKERFILE: ./listservice-backend/Dockerfile
  CLUSTER: listservice-ci-cluster
  SERVICE: listservice-ci-svc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      ecr_repo_url: ${{ steps.vars.outputs.ecr_repo_url }}
      sha_tag: ${{ steps.resolve.outputs.sha_tag }}
      env_tag: ${{ steps.resolve.outputs.env_tag }}
      pushed_tags: ${{ steps.compose.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-Global-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region "${AWS_REGION}" \
            | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

      - name: Set variables
        id: vars
        run: |
          echo "ecr_repo_url=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}" >> "$GITHUB_OUTPUT"

      - name: Resolve branch/env and SHA
        id: resolve
        shell: bash
        run: |
          BRANCH="${GITHUB_REF##*/}"
          case "$BRANCH" in
            staging) ENV_TAG="staging" ;;
            *)       ENV_TAG="$BRANCH" ;;
          esac
          echo "env_tag=${ENV_TAG}" >> "$GITHUB_OUTPUT"
          echo "sha_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Compose tag list (ECR only)
        id: compose
        shell: bash
        run: |
          set -euo pipefail
          ECR="${{ steps.vars.outputs.ecr_repo_url }}"
          SHA="${{ steps.resolve.outputs.sha_tag }}"
          ENV_TAG="${{ steps.resolve.outputs.env_tag }}"
          TAGS=()

          TAGS+=("${ECR}:${SHA}")
          TAGS+=("${ECR}:ci")
          TAGS+=("${ECR}:latest")

          if [[ "${ENV_TAG}" != "ci" && "${ENV_TAG}" != "latest" ]]; then
            TAGS+=("${ECR}:${ENV_TAG}")
          fi

          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.push_latest }}" == "true" ]]; then
            TAGS+=("${ECR}:latest")
          fi

          {
            echo "tags<<EOF"
            printf "%s\n" "${TAGS[@]}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (ECR)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.IMAGE_CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.compose.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: ci

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-CI-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure :ci or :latest image exists in ECR
        id: image
        shell: bash
        run: |
          set -euo pipefail
          if aws ecr describe-images --repository-name "${{ env.ECR_REPO }}" --image-ids imageTag=ci >/dev/null 2>&1; then
            echo "✅ Found ECR image tag :ci."
            echo "deploy_tag=ci" >> "$GITHUB_ENV"
          elif aws ecr describe-images --repository-name "${{ env.ECR_REPO }}" --image-ids imageTag=latest >/dev/null 2>&1; then
            echo "✅ Found ECR image tag :latest."
            echo "deploy_tag=latest" >> "$GITHUB_ENV"
          else
            echo "❌ Neither ':ci' nor ':latest' found in ${{ env.ECR_REPO }}."
            exit 1
          fi

      - name: Capture current desiredCount
        id: count
        shell: bash
        run: |
          set -euo pipefail
          CUR_COUNT=$(aws ecs describe-services \
            --cluster "${{ env.CLUSTER }}" \
            --services "${{ env.SERVICE }}" \
            --query 'services[0].desiredCount' --output text)
          if [ "$CUR_COUNT" = "None" ] || [ -z "$CUR_COUNT" ]; then
            CUR_COUNT=1
          fi
          echo "desired_count=$CUR_COUNT" >> "$GITHUB_OUTPUT"
          echo "Current desiredCount: $CUR_COUNT"

      - name: Force new deployment (keep desiredCount)
        shell: bash
        run: |
          set -euo pipefail
          aws ecs update-service \
            --cluster "${{ env.CLUSTER }}" \
            --service "${{ env.SERVICE }}" \
            --desired-count "${{ steps.count.outputs.desired_count }}" \
            --force-new-deployment \
            --no-cli-pager
          echo "🚀 Forced new deployment for ${{ env.SERVICE }} with desiredCount=${{ steps.count.outputs.desired_count }} using tag=${{ env.deploy_tag }}"

      - name: Wait for service to be stable
        if: ${{ inputs.skip_wait != 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          aws ecs wait services-stable \
            --cluster "${{ env.CLUSTER }}" \
            --services "${{ env.SERVICE }}"
          echo "✅ Service is stable."

      - name: Optional smoke test /health (HTTP 200)
        if: ${{ inputs.alb_dns != '' }}
        shell: bash
        run: |
          set -euo pipefail
          URL="http://${{ inputs.alb_dns }}/health"
          echo "Smoking: $URL"
          for i in {1..18}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
            if [ "$code" = "200" ]; then
              echo "✅ /health OK"
              exit 0
            fi
            echo "Attempt $i: got $code; retrying in 10s..."
            sleep 10
          done
          echo "❌ /health never returned 200"; exit 1
