name: Build and Publish Container

on:
  push:
    branches:
      - main
      - ci
      - staging
      - "*"   # feature branches

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 920120424372
  ECR_REPO: listservice-global
  IMAGE_NAME: listservice

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # GHCR
      id-token: write   # AWS OIDC

    outputs:
      sha_tag: ${{ steps.tags.outputs.sha_tag }}    # expose to downstream jobs
      env_tag: ${{ steps.tags.outputs.env_tag }}    # "latest" | "ci" | "staging" | "<branch>"
      ecr_repo_url: ${{ steps.vars.outputs.ecr_repo_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: ow
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-Global-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag values
        id: tags
        shell: bash
        run: |
          BRANCH="${GITHUB_REF##*/}"
          case "$BRANCH" in
            main)    ENV_TAG="latest"  ;;
            ci)      ENV_TAG="ci"      ;;
            staging) ENV_TAG="staging" ;;
            *)       ENV_TAG="$BRANCH" ;;
          esac
          echo "env_tag=$ENV_TAG"  >> $GITHUB_OUTPUT
          echo "sha_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set common vars
        id: vars
        run: |
          echo "ecr_repo_url=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push to BOTH registries:
      # - GHCR: :<env_tag> and :<sha>
      # - ECR: always :<sha>; and :latest only when branch == main (repo is MUTABLE)
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./listservice
          file: ./listservice/Dockerfile.ecs
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.env_tag }}
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.sha_tag }}
            ${{ steps.vars.outputs.ecr_repo_url }}:${{ steps.tags.outputs.sha_tag }}
            ${{ github.ref_name == 'main' && format('{0}:latest', steps.vars.outputs.ecr_repo_url) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
