name: Deploy to ECS (CI – latest)

on:
  # Trigger after successful build workflow
  workflow_run:
    workflows: ["Build and Publish (ECR)"]
    types: [completed]
    branches: [main, ci, staging]

  # Manual run any time
  workflow_dispatch:
    inputs:
      alb_dns:
        description: "Optional ALB DNS for smoke test"
        required: false
      skip_wait:
        description: "Skip waiting for service to stabilize"
        required: false
        default: "false"

permissions:
  id-token: write
  contents: read

concurrency:
  group: ecs-ci-deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: eu-central-1
  CLUSTER: listservice-ci-cluster
  SERVICE: listservice-ci-svc
  ECR_REPO: listservice-global
  AWS_ACCOUNT_ID: 920120424372

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-CI-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure :ci or :latest image exists in ECR
        id: image
        shell: bash
        run: |
          set -euo pipefail
          if aws ecr describe-images --repository-name "${{ env.ECR_REPO }}" --image-ids imageTag=ci >/dev/null 2>&1; then
            echo "✅ Found ECR image tag :ci."
            echo "deploy_tag=ci" >> "$GITHUB_ENV"
          elif aws ecr describe-images --repository-name "${{ env.ECR_REPO }}" --image-ids imageTag=latest >/dev/null 2>&1; then
            echo "✅ Found ECR image tag :latest."
            echo "deploy_tag=latest" >> "$GITHUB_ENV"
          else
            echo "❌ Neither ':ci' nor ':latest' found in ${{ env.ECR_REPO }}."
            exit 1
          fi

      - name: Capture current desiredCount
        id: count
        shell: bash
        run: |
          CUR_COUNT=$(aws ecs describe-services \
            --cluster "${{ env.CLUSTER }}" \
            --services "${{ env.SERVICE }}" \
            --query 'services[0].desiredCount' --output text)
          if [ "$CUR_COUNT" = "None" ] || [ -z "$CUR_COUNT" ]; then
            CUR_COUNT=1
          fi
          echo "desired_count=$CUR_COUNT" >> "$GITHUB_OUTPUT"
          echo "Current desiredCount: $CUR_COUNT"

      - name: Force new deployment (keep desiredCount)
        shell: bash
        run: |
          aws ecs update-service \
            --cluster "${{ env.CLUSTER }}" \
            --service "${{ env.SERVICE }}" \
            --desired-count "${{ steps.count.outputs.desired_count }}" \
            --force-new-deployment \
            --no-cli-pager
          echo "🚀 Forced new deployment for ${{ env.SERVICE }} with desiredCount=${{ steps.count.outputs.desired_count }} using tag=${{ env.deploy_tag }}"

      - name: Wait for service to be stable
        if: ${{ inputs.skip_wait != 'true' }}
        shell: bash
        run: |
          aws ecs wait services-stable \
            --cluster "${{ env.CLUSTER }}" \
            --services "${{ env.SERVICE }}"
          echo "✅ Service is stable."

      - name: Optional smoke test /health (HTTP 200)
        if: ${{ inputs.alb_dns != '' }}
        shell: bash
        run: |
          URL="http://${{ inputs.alb_dns }}/health"
          echo "Smoking: $URL"
          for i in {1..18}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
            if [ "$code" = "200" ]; then
              echo "✅ /health OK"
              exit 0
            fi
            echo "Attempt $i: got $code; retrying in 10s..."
            sleep 10
          done
          echo "❌ /health never returned 200"; exit 1
