name: Build and Publish Container

on:
  push:
    branches: 
      - main
      - staging
      - ci
      - "**"   # catch all feature branches safely
  workflow_dispatch: {}

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 920120424372
  ECR_REPO: listservice-global
  IMAGE_NAME: listservice

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR push
      id-token: write   # needed for AWS OIDC auth

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ----- Compute lowercase GHCR owner -----
      - name: Compute lowercase owner
        id: ow
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"

      # ----- Login to GHCR -----
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----- Login to AWS ECR -----
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/ListService-Global-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # ----- Derive Docker Tags -----
      - name: Set dynamic tags
        id: tags
        run: |
          BRANCH="${GITHUB_REF_NAME}"   # short branch name
          SAFE_BRANCH=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr '/' '-')

          case "$SAFE_BRANCH" in
            main) TAG="latest" ;;
            staging) TAG="staging" ;;
            ci) TAG="ci" ;;
            *) TAG="$SAFE_BRANCH" ;;
          esac

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # ----- Build & Push -----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR + ECR
        uses: docker/build-push-action@v6
        with:
          context: ./listservice
          file: ./listservice/Dockerfile.ecs
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.tag }}
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ steps.tags.outputs.tag }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
