name: Build and Publish to GHCR

on:
  push:
    branches: [ "main" ]   # add "ci", "staging" if you want env-based tags

env:
  IMAGE_NAME: listservice

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed to push to GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # GHCR requires lowercase owner in the image path
      - name: Compute lowercase owner
        id: ow
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (Dockerfile.ecs in listservice/)
        uses: docker/build-push-action@v6
        with:
          context: ./listservice                # <<< build context is the subfolder
          file: ./listservice/Dockerfile.ecs    # <<< dockerfile path
          push: true
          platforms: linux/amd64                # ECS default; keep even if you’re on Apple Silicon
          tags: |
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ steps.ow.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
