name: Infra (CI)

on:
  pull_request:
    paths:
      - 'infrastructure/listservice-infra/envs/ci/**'
      - '.github/workflows/infra-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/listservice-infra/envs/ci/**'
      - '.github/workflows/infra-ci.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'What to do'
        required: true
        type: choice
        options: [ plan, apply, destroy ]
        default: plan

permissions:
  id-token: write
  contents: read

concurrency:
  group: infra-ci-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: eu-central-1
  TF_ENV_DIR: infrastructure/listservice-infra/envs/ci
  TF_VARS_FILE: ci.tfvars
  TF_VERSION: 1.9.5

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action || 'auto' }} (CI)
    runs-on: ubuntu-latest
    environment: ci
    defaults:
      run:
        working-directory: ${{ env.TF_ENV_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-CI-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (remote state)
        run: terraform init -reconfigure -backend-config=backend.hcl

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      # ---------- PLAN ----------
      - name: Terraform Plan
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.action == 'plan' || github.event_name == 'push' }}
        run: terraform plan -no-color -out=tf.plan -var-file="${{ env.TF_VARS_FILE }}"

      - name: Upload Plan artifact (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-ci
          path: ${{ env.TF_ENV_DIR }}/tf.plan
          retention-days: 7

      # ---------- APPLY ----------
      - name: Terraform Apply (push to main or manual apply)
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve tf.plan

      # Optional quick smoke test
      - name: Smoke test /health
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply' }}
        run: |
          set -euo pipefail
          ALB_DNS="$(terraform output -raw alb_dns)"
          echo "Hitting http://$ALB_DNS/health"
          for i in {1..12}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "http://$ALB_DNS/health" || true)
            if [ "$code" = "200" ]; then
              echo "Health OK (200)."
              exit 0
            fi
            echo "Attempt $i: got $code, waiting 10s…"
            sleep 10
          done
          echo "Health check failed"; exit 1

      # ---------- DESTROY ----------
      - name: Terraform Destroy (manual only)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var-file="${{ env.TF_VARS_FILE }}"
