name: Infra (CI env)

on:
  pull_request:
    paths:
      - 'infrastructure/listservice-infra/modules/**'
      - 'infrastructure/listservice-infra/envs/ci/**'
      - '.github/workflows/infra-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/listservice-infra/modules/**'
      - 'infrastructure/listservice-infra/envs/ci/**'
      - '.github/workflows/infra-ci.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action'
        type: choice
        required: true
        options: [ plan, apply, destroy ]
        default: plan

permissions:
  id-token: write   # AWS OIDC
  contents: read

concurrency:
  group: infra-ci
  cancel-in-progress: false

env:
  AWS_REGION: eu-central-1
  TF_ENV_DIR: infrastructure/listservice-infra/envs/ci
  TF_VARS_FILE: ci.tfvars

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action || 'auto' }} (CI)
    runs-on: ubuntu-latest
    environment: ci
    defaults:
      run:
        working-directory: ${{ env.TF_ENV_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Optional but helpful: linters
      - name: Install tflint & tfsec
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          curl -sL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920120424372:role/ListService-CI-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (remote state)
        run: terraform init -reconfigure -backend-config=backend.hcl -input=false

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: tfsec
        run: tfsec . || true   # make strict later by removing "|| true"

      - name: Terraform Validate
        run: terraform validate -no-color

      # ---------- PLAN ----------
      - name: Terraform Plan
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.action == 'plan' || github.event.inputs.action == '' }}
        run: |
          terraform plan -var-file=${{ env.TF_VARS_FILE }} -out=tf.plan -no-color -input=false
          terraform show -json tf.plan > tfplan.json

      - name: Upload plan artifact
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.action == 'plan' || github.event.inputs.action == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-ci
          path: |
            ${{ env.TF_ENV_DIR }}/tf.plan
            ${{ env.TF_ENV_DIR }}/tfplan.json

      - name: Comment plan on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ env.TF_ENV_DIR }}/tfplan.json

      # ---------- APPLY ----------
      - name: Download plan (if exists)
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-ci
          path: ${{ env.TF_ENV_DIR }}
        continue-on-error: true

      - name: Terraform Apply (from plan if present)
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply' }}
        run: |
          if [ -f tf.plan ]; then
            terraform apply -auto-approve -input=false tf.plan
          else
            terraform apply -auto-approve -var-file=${{ env.TF_VARS_FILE }} -input=false
          fi

      # ---------- DESTROY ----------
      - name: Terraform Plan Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform plan -destroy -var-file=${{ env.TF_VARS_FILE }} -out=tf.destroy -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform apply -auto-approve -input=false tf.destroy
